#!/bin/bash

DATA=/mnt/data
CONFIG=$DATA/ocd_backend/settings.py

REDIS_IP=$REDIS_PORT_6379_TCP_ADDR
REDIS_PORT=$REDIS_PORT_6379_TCP_PORT
ES_IP=$ES_PORT_9200_TCP_ADDR
ES_PORT=$ES_PORT_9200_TCP_PORT


#CELERY_CONFIG = {
#    'BROKER_URL': 'redis://127.0.0.1:6379/0',
#        'CELERY_RESULT_BACKEND': 'redis://127.0.0.1:6379/0'
#        }
#ELASTICSEARCH_HOST = '127.0.0.1'
#ELASTICSEARCH_PORT = 9200

BROKER_SRC="'BROKER_URL': 'redis://"
BROKER_DST="'BROKER_URL': 'redis://$REDIS_IP:$REDIS_PORT/0',"
RESULT_SRC="CELERY_RESULT_BACKEND': 'redis://"
RESULT_DST="CELERY_RESULT_BACKEND': 'redis://$REDIS_IP:$REDIS_PORT/0'"
ES_SRC_HOST="ELASTICSEARCH_HOST = '"
ES_SRC_PORT="ELASTICSEARCH_PORT = "
ES_DST_HOST="ELASTICSEARCH_HOST = '$ES_IP'"
ES_DST_PORT="ELASTICSEARCH_PORT = $ES_PORT"

sed -i "s#$BROKER_SRC.*#$BROKER_DST#" $CONFIG
sed -i "s#$RESULT_SRC.*#$RESULT_DST#" $CONFIG
sed -i "s#$ES_SRC_HOST.*#$ES_DST_HOST#" $CONFIG
sed -i "s#$ES_SRC_PORT.*#$ES_DST_PORT#" $CONFIG

export C_FORCE_ROOT="true"
cd $DATA && /usr/local/bin/celery --app=ocd_backend:celery_app worker --loglevel=info --concurrency=2

